logo:
  path: themes/fixmy/logo.png
  url: ''
  use_default: false
_core:
  default_config_hash: _1KabmwhdZNi2DD3zwrsz8Hp4r3UpYT3nxHfnpJ0o58
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://localhost/themes/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
schemas:
  bootstrap: 8000
  fixmy: 8000
table: ''
