schemas:
  bootstrap: 8000
  fixmy: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://dev-fixmyberlin.pantheonsite.io/themes/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: 'public://logo_fmb_1.png'
  url: ''
  use_default: false
